-- Seed catalog_trips from viajes.json
-- Generated from viajes.json

INSERT INTO catalog_trips (id, title, image_url, duration_days, route, price_currency, price_base, price_single_supplement, price_taxes, includes, not_included, requirements, url, embedding_text, created_at, updated_at)
VALUES
(
    '910-dragones-de-asia',
    'DRAGONES DE ASIA',
    'http://www.suajili.com.ar//uploads/imagenes/paquetes/600x360/683ef1b94c785.jpg',
    22,
    ARRAY['Hanoi', 'Halong', 'Hue', 'Da Nang', 'Hoi An', 'Ho Chi Minh', 'Siem Reap', 'Bangkok', 'Phi Phi', 'Phuket'],
    'USD',
    7861,
    1844,
    1492,
    ARRAY['Aéreo internacional Turkish Airlines (Buenos Aires–Estambul–Hanoi // Phuket–Estambul–Buenos Aires)', 'Vuelos domésticos Vietnam (Hanoi/Hue, Danang/Ho Chi Minh)', 'Vuelos internacionales Ho Chi Minh/Siem Reap/Bangkok', 'Bangkok/Phuket + lancha Phuket/Phi Phi/Phuket', '17 noches hotel con desayuno + 1 noche crucero Halong (almuerzo/cena)', '13 comidas incluidas', 'Guías locales en español + entradas + propinas', 'Seguro Universal Assistance + tour leader desde Argentina (mín 10 pax)'],
    ARRAY['Bebidas en comidas', 'Comidas/bebidas no especificadas', 'Servicios no mencionados', 'Gastos personales y opcionales'],
    ARRAY['Pasaporte con vencimiento mayor a 6 meses al regreso', 'Vacuna fiebre amarilla (obligatoria)', 'Visa Vietnam (online) y Camboya (on arrival)'],
    'https://www.suajili.com.ar/viajes_en_grupo/viaje/910/dragones-de-asia',
    'Dragones de Asia (22 días). Ruta: Hanoi, Halong, Hue, Hoi An, Ho Chi Minh, Siem Reap, Bangkok, Phi Phi, Phuket. Próxima salida 24/01/2026. Incluye aéreo internacional Turkish + vuelos internos e internacionales en Asia, hoteles con desayuno, crucero Halong, 13 comidas, guías en español, entradas, propinas, seguro y tour leader desde Argentina. Precio desde USD 7861 + imp aprox USD 1492. Requiere vacuna fiebre amarilla + visas Vietnam/Camboya.',
    NOW(),
    NOW()
),
(
    '911-fiordos-y-capitales-nordicas',
    'FIORDOS Y CAPITALES NÓRDICAS',
    'http://www.suajili.com.ar//uploads/imagenes/paquetes/600x360/a1b2c3d4e5f6.jpg',
    15,
    ARRAY['Copenhague', 'Oslo', 'Fiordo de Geiranger', 'Bergen', 'Flåm', 'Estocolmo'],
    'USD',
    6420,
    1290,
    980,
    ARRAY['Aéreo internacional con KLM / Air France desde Buenos Aires (ida y vuelta)', 'Traslados de llegada y salida en cada destino', '10 noches de alojamiento con desayuno (o similar)', '9 comidas incluidas (aprox.)', 'Visitas con guía local de habla hispana según itinerario', 'Entradas a los lugares de visita según programa', 'Seguro de asistencia médica + kit de viaje', 'Tour leader acompañante desde Argentina con mínimo 10 pasajeros', 'Crucero por fiordo (1 noche a bordo)'],
    ARRAY['Bebidas en las comidas', 'Comidas y bebidas no especificadas', 'Servicios no mencionados', 'Gastos personales y actividades opcionales'],
    ARRAY['Pasaporte vigente 6+ meses', 'Seguro de viaje recomendado', 'Requiere autorización/visa según nacionalidad (Schengen)'],
    'https://www.suajili.com.ar/viajes_en_grupo/viaje/911/fiordos-y-capitales-nordicas',
    'Fiordos Y Capitales Nórdicas (15 días). Ruta: Copenhague, Oslo, Fiordo de Geiranger, Bergen, Flåm, Estocolmo. Próxima salida 07/06/2026. Incluye aéreo internacional KLM / Air France, traslados, hoteles con desayuno, visitas guiadas en español y seguro. Precio desde USD 6420 + imp aprox USD 980. Requisitos: Pasaporte vigente 6+ meses + Seguro de viaje recomendado + Requiere autorización/visa según nacionalidad (Schengen).',
    NOW(),
    NOW()
),
(
    '912-safari-y-zanzibar',
    'SAFARI EN TANZANIA + ZANZÍBAR',
    'http://www.suajili.com.ar//uploads/imagenes/paquetes/600x360/b7c8d9e0f1a2.jpg',
    12,
    ARRAY['Arusha', 'Tarangire', 'Serengeti', 'Ngorongoro', 'Zanzíbar (Nungwi)'],
    'USD',
    5980,
    1120,
    860,
    ARRAY['Aéreo internacional con Ethiopian Airlines desde Buenos Aires (ida y vuelta)', 'Traslados de llegada y salida en cada destino', '7 noches de alojamiento con desayuno (o similar)', '7 comidas incluidas (aprox.)', 'Visitas con guía local de habla hispana según itinerario', 'Entradas a los lugares de visita según programa', 'Seguro de asistencia médica + kit de viaje', 'Tour leader acompañante desde Argentina con mínimo 10 pasajeros', 'Jeep 4x4 en safari con guía experto', '2 noches en lodge dentro de parque'],
    ARRAY['Bebidas en las comidas', 'Comidas y bebidas no especificadas', 'Servicios no mencionados', 'Gastos personales y actividades opcionales'],
    ARRAY['Pasaporte vigente 6+ meses', 'Vacuna fiebre amarilla (según ruta)', 'Visa Tanzania (on arrival/online)'],
    'https://www.suajili.com.ar/viajes_en_grupo/viaje/912/safari-y-zanzibar',
    'Safari En Tanzania + Zanzíbar (12 días). Ruta: Arusha, Tarangire, Serengeti, Ngorongoro, Zanzíbar (Nungwi). Próxima salida 15/08/2026. Incluye aéreo internacional Ethiopian Airlines, traslados, hoteles con desayuno, visitas guiadas en español y seguro. Precio desde USD 5980 + imp aprox USD 860. Requisitos: Pasaporte vigente 6+ meses + Vacuna fiebre amarilla (según ruta) + Visa Tanzania (on arrival/online).',
    NOW(),
    NOW()
),
(
    '913-japon-en-otono',
    'JAPÓN EN OTOÑO',
    'http://www.suajili.com.ar//uploads/imagenes/paquetes/600x360/c3d4e5f6a7b8.jpg',
    14,
    ARRAY['Tokio', 'Nikkō', 'Hakone', 'Kioto', 'Nara', 'Hiroshima', 'Miyajima', 'Osaka'],
    'USD',
    7290,
    1680,
    1150,
    ARRAY['Aéreo internacional con Qatar Airways desde Buenos Aires (ida y vuelta)', 'Traslados de llegada y salida en cada destino', '9 noches de alojamiento con desayuno (o similar)', '8 comidas incluidas (aprox.)', 'Visitas con guía local de habla hispana según itinerario', 'Entradas a los lugares de visita según programa', 'Seguro de asistencia médica + kit de viaje', 'Tour leader acompañante desde Argentina con mínimo 10 pasajeros', 'Japan Rail Pass (segmentos incluidos)', 'Experiencia onsen en Hakone'],
    ARRAY['Bebidas en las comidas', 'Comidas y bebidas no especificadas', 'Servicios no mencionados', 'Gastos personales y actividades opcionales'],
    ARRAY['Pasaporte vigente 6+ meses', 'Seguro médico obligatorio/recomendado', 'Requisitos de ingreso pueden variar'],
    'https://www.suajili.com.ar/viajes_en_grupo/viaje/913/japon-en-otono',
    'Japón En Otoño (14 días). Ruta: Tokio, Nikkō, Hakone, Kioto, Nara, Hiroshima, Miyajima, Osaka. Próxima salida 10/10/2026. Incluye aéreo internacional Qatar Airways, traslados, hoteles con desayuno, visitas guiadas en español y seguro. Precio desde USD 7290 + imp aprox USD 1150. Requisitos: Pasaporte vigente 6+ meses + Seguro médico obligatorio/recomendado + Requisitos de ingreso pueden variar.',
    NOW(),
    NOW()
),
(
    '914-patagonia-epica',
    'PATAGONIA ÉPICA',
    'http://www.suajili.com.ar//uploads/imagenes/paquetes/600x360/d9e0f1a2b3c4.jpg',
    10,
    ARRAY['El Calafate', 'Glaciar Perito Moreno', 'El Chaltén', 'Ushuaia', 'Parque Nacional Tierra del Fuego'],
    'USD',
    2890,
    740,
    320,
    ARRAY['Aéreo internacional con Aerolíneas Argentinas (domésticos) desde Buenos Aires (ida y vuelta)', 'Traslados de llegada y salida en cada destino', '7 noches de alojamiento con desayuno (o similar)', '6 comidas incluidas (aprox.)', 'Visitas con guía local de habla hispana según itinerario', 'Entradas a los lugares de visita según programa', 'Seguro de asistencia médica + kit de viaje', 'Tour leader acompañante desde Argentina con mínimo 10 pasajeros', 'Excursión al Glaciar Perito Moreno', 'Navegación canal Beagle'],
    ARRAY['Bebidas en las comidas', 'Comidas y bebidas no especificadas', 'Servicios no mencionados', 'Gastos personales y actividades opcionales'],
    ARRAY['DNI o pasaporte (según tramos)', 'Ropa de abrigo/impermeable recomendada'],
    'https://www.suajili.com.ar/viajes_en_grupo/viaje/914/patagonia-epica',
    'Patagonia Épica (10 días). Ruta: El Calafate, Glaciar Perito Moreno, El Chaltén, Ushuaia, Parque Nacional Tierra del Fuego. Próxima salida 21/03/2026. Incluye aéreo internacional Aerolíneas Argentinas (domésticos), traslados, hoteles con desayuno, visitas guiadas en español y seguro. Precio desde USD 2890 + imp aprox USD 320. Requisitos: DNI o pasaporte (según tramos) + Ropa de abrigo/impermeable recomendada.',
    NOW(),
    NOW()
),
(
    '915-marruecos-y-andalucia',
    'MARRUECOS + ANDALUCÍA',
    'http://www.suajili.com.ar//uploads/imagenes/paquetes/600x360/e5f6a7b8c9d0.jpg',
    13,
    ARRAY['Madrid', 'Sevilla', 'Córdoba', 'Granada', 'Tánger', 'Chefchaouen', 'Fez', 'Marrakech'],
    'USD',
    4680,
    990,
    720,
    ARRAY['Aéreo internacional con Iberia desde Buenos Aires (ida y vuelta)', 'Traslados de llegada y salida en cada destino', '8 noches de alojamiento con desayuno (o similar)', '7 comidas incluidas (aprox.)', 'Visitas con guía local de habla hispana según itinerario', 'Entradas a los lugares de visita según programa', 'Seguro de asistencia médica + kit de viaje', 'Tour leader acompañante desde Argentina con mínimo 10 pasajeros', 'Tren de alta velocidad en España (1 tramo)', 'Noche en riad en Marrakech'],
    ARRAY['Bebidas en las comidas', 'Comidas y bebidas no especificadas', 'Servicios no mencionados', 'Gastos personales y actividades opcionales'],
    ARRAY['Pasaporte vigente 6+ meses', 'Visa Marruecos según nacionalidad'],
    'https://www.suajili.com.ar/viajes_en_grupo/viaje/915/marruecos-y-andalucia',
    'Marruecos + Andalucía (13 días). Ruta: Madrid, Sevilla, Córdoba, Granada, Tánger, Chefchaouen, Fez, Marrakech. Próxima salida 12/04/2026. Incluye aéreo internacional Iberia, traslados, hoteles con desayuno, visitas guiadas en español y seguro. Precio desde USD 4680 + imp aprox USD 720. Requisitos: Pasaporte vigente 6+ meses + Visa Marruecos según nacionalidad.',
    NOW(),
    NOW()
),
(
    '916-peru-mistico',
    'PERÚ MÍSTICO',
    'http://www.suajili.com.ar//uploads/imagenes/paquetes/600x360/f1a2b3c4d5e6.jpg',
    9,
    ARRAY['Lima', 'Cusco', 'Valle Sagrado', 'Machu Picchu', 'Puno', 'Lago Titicaca'],
    'USD',
    2450,
    620,
    290,
    ARRAY['Aéreo internacional con LATAM (regional) desde Buenos Aires (ida y vuelta)', 'Traslados de llegada y salida en cada destino', '7 noches de alojamiento con desayuno (o similar)', '6 comidas incluidas (aprox.)', 'Visitas con guía local de habla hispana según itinerario', 'Entradas a los lugares de visita según programa', 'Seguro de asistencia médica + kit de viaje', 'Tour leader acompañante desde Argentina con mínimo 10 pasajeros', 'Tren a Machu Picchu (categoría turística)', 'Almuerzo pachamanca (experiencia)'],
    ARRAY['Bebidas en las comidas', 'Comidas y bebidas no especificadas', 'Servicios no mencionados', 'Gastos personales y actividades opcionales'],
    ARRAY['Pasaporte vigente 6+ meses', 'Vacuna fiebre amarilla recomendada (selva)', 'Altura: consulta médica si corresponde'],
    'https://www.suajili.com.ar/viajes_en_grupo/viaje/916/peru-mistico',
    'Perú Místico (9 días). Ruta: Lima, Cusco, Valle Sagrado, Machu Picchu, Puno, Lago Titicaca. Próxima salida 02/05/2026. Incluye aéreo internacional LATAM (regional), traslados, hoteles con desayuno, visitas guiadas en español y seguro. Precio desde USD 2450 + imp aprox USD 290. Requisitos: Pasaporte vigente 6+ meses + Vacuna fiebre amarilla recomendada (selva) + Altura: consulta médica si corresponde.',
    NOW(),
    NOW()
),
(
    '917-egipto-y-nilo',
    'EGIPTO Y CRUCERO POR EL NILO',
    'http://www.suajili.com.ar//uploads/imagenes/paquetes/600x360/0a1b2c3d4e5f.jpg',
    11,
    ARRAY['El Cairo', 'Giza', 'Luxor', 'Edfu', 'Kom Ombo', 'Asuán'],
    'USD',
    5190,
    1080,
    840,
    ARRAY['Aéreo internacional con Turkish Airlines desde Buenos Aires (ida y vuelta)', 'Traslados de llegada y salida en cada destino', '7 noches de alojamiento con desayuno (o similar)', '6 comidas incluidas (aprox.)', 'Visitas con guía local de habla hispana según itinerario', 'Entradas a los lugares de visita según programa', 'Seguro de asistencia médica + kit de viaje', 'Tour leader acompañante desde Argentina con mínimo 10 pasajeros', 'Crucero por el Nilo (3 noches) con pensión completa'],
    ARRAY['Bebidas en las comidas', 'Comidas y bebidas no especificadas', 'Servicios no mencionados', 'Gastos personales y actividades opcionales'],
    ARRAY['Pasaporte vigente 6+ meses', 'Visa Egipto (on arrival/online)', 'Seguro médico recomendado'],
    'https://www.suajili.com.ar/viajes_en_grupo/viaje/917/egipto-y-nilo',
    'Egipto Y Crucero Por El Nilo (11 días). Ruta: El Cairo, Giza, Luxor, Edfu, Kom Ombo, Asuán. Próxima salida 03/11/2026. Incluye aéreo internacional Turkish Airlines, traslados, hoteles con desayuno, visitas guiadas en español y seguro. Precio desde USD 5190 + imp aprox USD 840. Requisitos: Pasaporte vigente 6+ meses + Visa Egipto (on arrival/online) + Seguro médico recomendado.',
    NOW(),
    NOW()
),
(
    '918-islandia-y-auroras',
    'ISLANDIA Y AURORAS BOREALES',
    'http://www.suajili.com.ar//uploads/imagenes/paquetes/600x360/1f2e3d4c5b6a.jpg',
    8,
    ARRAY['Reikiavik', 'Círculo Dorado', 'Vík', 'Jökulsárlón', 'Blue Lagoon'],
    'USD',
    4120,
    980,
    650,
    ARRAY['Aéreo internacional con Icelandair (con conexiones) desde Buenos Aires (ida y vuelta)', 'Traslados de llegada y salida en cada destino', '7 noches de alojamiento con desayuno (o similar)', '6 comidas incluidas (aprox.)', 'Visitas con guía local de habla hispana según itinerario', 'Entradas a los lugares de visita según programa', 'Seguro de asistencia médica + kit de viaje', 'Tour leader acompañante desde Argentina con mínimo 10 pasajeros', 'Caza de auroras (2 salidas)', 'Baño termal Blue Lagoon'],
    ARRAY['Bebidas en las comidas', 'Comidas y bebidas no especificadas', 'Servicios no mencionados', 'Gastos personales y actividades opcionales'],
    ARRAY['Pasaporte vigente 6+ meses', 'Seguro de viaje recomendado', 'Clima extremo: equipamiento obligatorio'],
    'https://www.suajili.com.ar/viajes_en_grupo/viaje/918/islandia-y-auroras',
    'Islandia Y Auroras Boreales (8 días). Ruta: Reikiavik, Círculo Dorado, Vík, Jökulsárlón, Blue Lagoon. Próxima salida 05/02/2027. Incluye aéreo internacional Icelandair (con conexiones), traslados, hoteles con desayuno, visitas guiadas en español y seguro. Precio desde USD 4120 + imp aprox USD 650. Requisitos: Pasaporte vigente 6+ meses + Seguro de viaje recomendado + Clima extremo: equipamiento obligatorio.',
    NOW(),
    NOW()
),
(
    '919-mexico-yucatan',
    'MÉXICO: YUCATÁN Y CARIBE',
    'http://www.suajili.com.ar//uploads/imagenes/paquetes/600x360/2a3b4c5d6e7f.jpg',
    10,
    ARRAY['Ciudad de México', 'Teotihuacán', 'Mérida', 'Chichén Itzá', 'Tulum', 'Playa del Carmen'],
    'USD',
    3380,
    820,
    430,
    ARRAY['Aéreo internacional con Aeroméxico desde Buenos Aires (ida y vuelta)', 'Traslados de llegada y salida en cada destino', '7 noches de alojamiento con desayuno (o similar)', '6 comidas incluidas (aprox.)', 'Visitas con guía local de habla hispana según itinerario', 'Entradas a los lugares de visita según programa', 'Seguro de asistencia médica + kit de viaje', 'Tour leader acompañante desde Argentina con mínimo 10 pasajeros', 'Visita a cenotes en Yucatán', 'Clase de cocina mexicana'],
    ARRAY['Bebidas en las comidas', 'Comidas y bebidas no especificadas', 'Servicios no mencionados', 'Gastos personales y actividades opcionales'],
    ARRAY['Pasaporte vigente 6+ meses', 'Requisitos de ingreso pueden variar'],
    'https://www.suajili.com.ar/viajes_en_grupo/viaje/919/mexico-yucatan',
    'México: Yucatán Y Caribe (10 días). Ruta: Ciudad de México, Teotihuacán, Mérida, Chichén Itzá, Tulum, Playa del Carmen. Próxima salida 18/07/2026. Incluye aéreo internacional Aeroméxico, traslados, hoteles con desayuno, visitas guiadas en español y seguro. Precio desde USD 3380 + imp aprox USD 430. Requisitos: Pasaporte vigente 6+ meses + Requisitos de ingreso pueden variar.',
    NOW(),
    NOW()
);

-- Seed catalog_trip_departures
INSERT INTO catalog_trip_departures (catalog_trip_id, departure_date, return_date, status)
VALUES
('910-dragones-de-asia', '2026-01-24', '2026-02-14', 'open'),
('911-fiordos-y-capitales-nordicas', '2026-06-07', '2026-06-21', 'open'),
('912-safari-y-zanzibar', '2026-08-15', '2026-08-26', 'open'),
('913-japon-en-otono', '2026-10-10', '2026-10-23', 'open'),
('914-patagonia-epica', '2026-03-21', '2026-03-30', 'open'),
('915-marruecos-y-andalucia', '2026-04-12', '2026-04-24', 'open'),
('916-peru-mistico', '2026-05-02', '2026-05-10', 'open'),
('917-egipto-y-nilo', '2026-11-03', '2026-11-13', 'open'),
('918-islandia-y-auroras', '2027-02-05', '2027-02-12', 'open'),
('919-mexico-yucatan', '2026-07-18', '2026-07-27', 'open');
