/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/io.ktor.server.http.content.TailcardSelector@68dd39d2/static/{...}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a list of conversations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.ConversationDto"][];
                    };
                };
            };
        };
        put?: never;
        /** @description Create a new conversation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.CreateConversationRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.CreateConversationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversationId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a list of conversation messages */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.MessageDto"][];
                    };
                };
            };
        };
        put?: never;
        /** @description Append a user message */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.CreateMessageRequest"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.MessageDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversationId}/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConversationDto */
        "com.francoherrero.ai_agent_multiplatform.model.ConversationDto": {
            /** String */
            id: string;
            /** String */
            title?: null | string;
            /** String */
            createdAt: string;
            /** String */
            updatedAt: string;
        };
        /** CreateConversationRequest */
        "com.francoherrero.ai_agent_multiplatform.model.CreateConversationRequest": {
            /** String */
            title?: null | string;
        };
        /** CreateConversationResponse */
        "com.francoherrero.ai_agent_multiplatform.model.CreateConversationResponse": {
            conversation: components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.ConversationDto"];
        };
        /** MessageDto */
        "com.francoherrero.ai_agent_multiplatform.model.MessageDto": {
            /** String */
            id: string;
            /** String */
            conversationId: string;
            /** String */
            role: string;
            /** String */
            content: string;
            /** String */
            clientMessageId?: null | string;
            /** String */
            status: string;
            /** String */
            createdAt: string;
        };
        /** CreateMessageRequest */
        "com.francoherrero.ai_agent_multiplatform.model.CreateMessageRequest": {
            /** String */
            content: string;
            /** String */
            clientMessageId?: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
