/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/io.ktor.server.http.content.TailcardSelector@6010d0d1/static/{...}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.routes.LoginRequestBody"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.auth.AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a list of conversations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.ConversationDto"][];
                    };
                };
            };
        };
        put?: never;
        /** @description Create a new conversation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.CreateConversationRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.CreateConversationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversationId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a list of conversation messages */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.MessageDto"][];
                    };
                };
            };
        };
        put?: never;
        /** @description Append a user message */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.CreateMessageRequest"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.MessageDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversationId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/trips/{tripId}/travelers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/trips/{tripId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List catalog trips (paginated) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.CatalogTripDto"][];
                    };
                };
            };
        };
        put?: never;
        /** @description Create a new catalog trip */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.CatalogTripRequest"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.CatalogTripDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single catalog trip by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.CatalogTripDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description Delete a catalog trip */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.CatalogTripDto"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** @description Update an existing catalog trip */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.CatalogTripRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.CatalogTripDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List users (paginated) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.UserDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single user by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.UserDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description Delete user profile */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.UserDto"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** @description Update user profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.UserRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.UserDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List trips (paginated) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.UserTripDto"][];
                    };
                };
            };
        };
        put?: never;
        /** @description Create a new trip */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.AdminTripRequest"];
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.UserTripDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single trip by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.UserTripDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description Delete a trip */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.UserTripDto"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** @description Update an existing trip */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.AdminTripRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.UserTripDto"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** LoginRequestBody */
        "com.francoherrero.ai_agent_multiplatform.routes.LoginRequestBody": {
            /** String */
            email: string;
            /** String */
            password: string;
        };
        /** User */
        "com.francoherrero.ai_agent_multiplatform.auth.User": {
            /** String */
            id: string;
            /** String */
            email: string;
            user_metadata?: null | components["schemas"]["com.francoherrero.ai_agent_multiplatform.auth.UserMetadata"];
        };
        /** UserMetadata */
        "com.francoherrero.ai_agent_multiplatform.auth.UserMetadata": {
            /** String */
            full_name?: null | string;
        };
        /** AuthResponse */
        "com.francoherrero.ai_agent_multiplatform.auth.AuthResponse": {
            /** String */
            access_token: string;
            /** String */
            refresh_token: string;
            /** String */
            token_type: string;
            /**
             * Long
             * Format: int64
             */
            expires_in: number;
            /**
             * Long
             * Format: int64
             */
            expires_at?: null | number;
            user: components["schemas"]["com.francoherrero.ai_agent_multiplatform.auth.User"];
        };
        /** ConversationDto */
        "com.francoherrero.ai_agent_multiplatform.model.ConversationDto": {
            /** String */
            id: string;
            /** String */
            title?: null | string;
            /** String */
            createdAt: string;
            /** String */
            updatedAt: string;
        };
        /** CreateConversationRequest */
        "com.francoherrero.ai_agent_multiplatform.model.CreateConversationRequest": {
            /** String */
            title?: null | string;
        };
        /** CreateConversationResponse */
        "com.francoherrero.ai_agent_multiplatform.model.CreateConversationResponse": {
            conversation: components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.ConversationDto"];
        };
        /** MessageDto */
        "com.francoherrero.ai_agent_multiplatform.model.MessageDto": {
            /** String */
            id: string;
            /** String */
            conversationId: string;
            /** String */
            role: string;
            /** String */
            content: string;
            /** String */
            clientMessageId?: null | string;
            /** String */
            status: string;
            /** String */
            createdAt: string;
        };
        /** CreateMessageRequest */
        "com.francoherrero.ai_agent_multiplatform.model.CreateMessageRequest": {
            /** String */
            content: string;
            /** String */
            clientMessageId?: null | string;
        };
        /** CatalogTripDto */
        "com.francoherrero.ai_agent_multiplatform.model.CatalogTripDto": {
            /**
             * Int
             * Format: int32
             */
            id: number;
            /** String */
            title: string;
            /** String */
            image_url?: null | string;
            /**
             * Int
             * Format: int32
             */
            duration_days: number;
            /** ArrayList<String> */
            route: string[];
            /** String */
            price_currency?: null | string;
            /**
             * Double
             * Format: double
             */
            price_base?: null | number;
            /**
             * Double
             * Format: double
             */
            price_single_supplement?: null | number;
            /**
             * Double
             * Format: double
             */
            price_taxes?: null | number;
            /** ArrayList<String> */
            includes?: null | string[];
            /** ArrayList<String> */
            not_included?: null | string[];
            /** ArrayList<String> */
            requirements?: null | string[];
            /** String */
            url?: null | string;
            /** String */
            created_at: string;
            /** String */
            updated_at: string;
        };
        /** CatalogTripRequest */
        "com.francoherrero.ai_agent_multiplatform.model.CatalogTripRequest": {
            /**
             * Int
             * Format: int32
             */
            id?: null | number;
            /** String */
            title?: null | string;
            /** String */
            image_url?: null | string;
            /**
             * Int
             * Format: int32
             */
            duration_days?: null | number;
            /** ArrayList<String> */
            route?: null | string[];
            /** String */
            price_currency?: null | string;
            /**
             * Double
             * Format: double
             */
            price_base?: null | number;
            /**
             * Double
             * Format: double
             */
            price_single_supplement?: null | number;
            /**
             * Double
             * Format: double
             */
            price_taxes?: null | number;
            /** ArrayList<String> */
            includes?: null | string[];
            /** ArrayList<String> */
            not_included?: null | string[];
            /** ArrayList<String> */
            requirements?: null | string[];
            /** String */
            url?: null | string;
        };
        /** UserDto */
        "com.francoherrero.ai_agent_multiplatform.model.UserDto": {
            /** String */
            id: string;
            /** String */
            email: string;
            /** String */
            phone?: null | string;
            /** String */
            first_name?: null | string;
            /** String */
            last_name?: null | string;
        };
        /** UserRequest */
        "com.francoherrero.ai_agent_multiplatform.model.UserRequest": {
            /** String */
            first_name?: null | string;
            /** String */
            last_name?: null | string;
        };
        /** UserTripDto */
        "com.francoherrero.ai_agent_multiplatform.model.UserTripDto": {
            /** String */
            id: string;
            /** String */
            user_id: string;
            type: components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.TripType"];
            /**
             * Int
             * Format: int32
             */
            catalog_trip_id?: null | number;
            /** String */
            departure_id?: null | string;
            /** String */
            title?: null | string;
            status: components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.TripStatus"];
            /** String */
            departure_date?: null | string;
            /** String */
            return_date?: null | string;
            /**
             * Double
             * Format: double
             */
            total_price?: null | number;
            /** String */
            currency?: null | string;
            /** String */
            notes?: null | string;
            /** String */
            created_at: string;
            /** String */
            updated_at: string;
            /** String */
            trip_title?: null | string;
            /** String */
            trip_image_url?: null | string;
            /** ArrayList<String> */
            trip_route?: null | string[];
            /**
             * Int
             * Format: int32
             */
            trip_duration_days?: null | number;
            /** ArrayList<UserTripDestinationDto> */
            destinations?: null | components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.UserTripDestinationDto"][];
            /** ArrayList<TravelerDto> */
            travelers?: null | components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.TravelerDto"][];
            /** ArrayList<TripDocumentDto> */
            documents?: null | components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.TripDocumentDto"][];
        };
        /**
         * TripType
         * @enum {string}
         */
        "com.francoherrero.ai_agent_multiplatform.model.TripType": "group" | "custom";
        /**
         * TripStatus
         * @enum {string}
         */
        "com.francoherrero.ai_agent_multiplatform.model.TripStatus": "pending" | "confirmed" | "paid" | "completed" | "cancelled";
        /** UserTripDestinationDto */
        "com.francoherrero.ai_agent_multiplatform.model.UserTripDestinationDto": {
            /** String */
            id: string;
            /** String */
            user_trip_id: string;
            /** String */
            destination_name: string;
            /** String */
            country?: null | string;
            /**
             * Int
             * Format: int32
             */
            sequence: number;
            /** String */
            start_date?: null | string;
            /** String */
            end_date?: null | string;
            /**
             * Int
             * Format: int32
             */
            nights?: null | number;
            /** String */
            accommodation?: null | string;
            /** String */
            notes?: null | string;
            /** String */
            created_at?: null | string;
        };
        /** TravelerDto */
        "com.francoherrero.ai_agent_multiplatform.model.TravelerDto": {
            /** String */
            id: string;
            /** String */
            user_trip_id: string;
            /** String */
            full_name: string;
            /** String */
            email?: null | string;
            /** String */
            phone?: null | string;
            /** String */
            birth_date?: null | string;
            /** String */
            nationality?: null | string;
            document_type?: null | components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.TravelerDocumentType"];
            /** String */
            document_number?: null | string;
            /** String */
            document_expiry?: null | string;
            /** Boolean */
            is_primary: boolean;
            /** String */
            created_at?: null | string;
            /** String */
            updated_at?: null | string;
        };
        /**
         * TravelerDocumentType
         * @enum {string}
         */
        "com.francoherrero.ai_agent_multiplatform.model.TravelerDocumentType": "passport" | "dni" | "other";
        /** TripDocumentDto */
        "com.francoherrero.ai_agent_multiplatform.model.TripDocumentDto": {
            /** String */
            id: string;
            /** String */
            user_trip_id: string;
            /** String */
            name: string;
            type: components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.DocumentType"];
            /** String */
            storage_path: string;
            /**
             * Int
             * Format: int32
             */
            file_size?: null | number;
            /** String */
            mime_type?: null | string;
            /** String */
            traveler_id?: null | string;
            /** String */
            created_at?: null | string;
        };
        /**
         * DocumentType
         * @enum {string}
         */
        "com.francoherrero.ai_agent_multiplatform.model.DocumentType": "ticket" | "voucher" | "itinerary" | "insurance" | "passport" | "visa" | "other";
        /** AdminTripRequest */
        "com.francoherrero.ai_agent_multiplatform.model.AdminTripRequest": {
            /** String */
            user_id?: null | string;
            type?: null | components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.TripType"];
            /**
             * Int
             * Format: int32
             */
            catalog_trip_id?: null | number;
            /** String */
            departure_id?: null | string;
            /** String */
            title?: null | string;
            status?: null | components["schemas"]["com.francoherrero.ai_agent_multiplatform.model.TripStatus"];
            /** String */
            departure_date?: null | string;
            /** String */
            return_date?: null | string;
            /**
             * Double
             * Format: double
             */
            total_price?: null | number;
            /** String */
            currency?: null | string;
            /** String */
            notes?: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
